### ISSUE TITLE
Flowupload Dashboard Widget

### ISSUE THREAD

**Issue by sunjam** [e-alfred/flowupload#198]
Inspired by #10, but this humble request is for adding Flowupload as a Dashboard Widget.  This would be an amazing way to upload files directly from the Dashboard menu, especially if destinations could be defined under very stripped-down widget settings.  Or, it could be used to just track those files and folders most recently uploaded in flow.

Thanks for considering!

**Comment by JonathanTreffler** [comment]
I generally love integrating everything together in Nextcloud (in this case Flowupload with Dashboard), but in this case i don't really see a big use case for this (but you can prove me wrong :) ).



> This would be an amazing way to upload files directly from the Dashboard menu

Generally a good idea and definitely possible, but is it really practical ?

> track those files and folders most recently uploaded in flow

I personally don't see flowupload as a second upload type, but just a different upload method, to achieve the same thing.
From a server perspective, after the upload is done it looks the same as if it was uploaded with the standard upload function.
flowupload currently does not keep track which files got uploaded, because the activity app already does that.
for example:
![image](https://user-images.githubusercontent.com/28999431/95665174-199ce780-0b4e-11eb-8682-5f173b82e64b.png)
The bottom one was uploaded using the built in upload and the second using flowupload.
It looks the same on purpose.

So in my opinion a general last uploads (not only from flowupload) widget would make more sense.

**Comment by sunjam** [comment]
General last uploads widget sounds great.  Do you think that would be a
more appropriate request for the activity app?

**Comment by JonathanTreffler** [comment]
> Do you think that would be a more appropriate request for the activity app?

Great idea.

**Comment by sunjam** [comment]
We'll I still think it would be awesome to have a widget with starred directories for uploading files while in Dashboard mode.  Makes sense if it isn't practical. :+1:
