### ISSUE TITLE
Select folder not showing up Flowupload next cloud

### ISSUE THREAD

**Issue by Jon089** [e-alfred/flowupload#59]
Installed Flowupload, and first of all would like to say that It works great, however when uploading it always creates and uploads the files to a Flowupload folder and does not give me the option to "select" a folder for the upload. 

I have seen on a few screenshots that next to the button "select file" there should be a button "select folder" but for some reason it is not showing up. So I can't select the folder to upload the files too. 
<img width="760" alt="Screenshot 2019-05-23 at 20 06 31" src="https://user-images.githubusercontent.com/50912601/58275844-49e7b880-7d96-11e9-8d98-d6bf61408fb7.png">

**Comment by Jon089** [comment]
Here is a screenshot where it shows up, but disapears after 
<img width="919" alt="Screenshot 2019-05-23 at 20 13 52" src="https://user-images.githubusercontent.com/50912601/58276299-60424400-7d97-11e9-80da-d4d6c84938eb.png">

**Comment by e-alfred** [comment]
Which browser are you using? This "Select folder" upload button just allows you to upload a complete folder instead of single files (but only on Firefox and Chromium-based browsers), it is not intended to select a destination folder on the server. We have a separate issue for that here: https://github.com/e-alfred/flowupload/issues/4

**Comment by Jon089** [comment]
Hi E-alfred, 

You are completely right! It is a browser issue, I didn't think of that, infant it works fine on Chrome or Firefox, it doesn't show up on Safari only. 

I will take a look at the link you mentioned fir #4 thank you !
